import Home from "../pages/Home/Home";
import Login from "../pages/Auth/Login";
import Register from "../pages/Auth/Register";
import Logout from "../pages/Auth/Logout";
import View from "./Blog/View";
import Create from "./Blog/Create";
import Edit from "./Blog/Edit";
import Delete from "./Blog/Delete";
import About from "../pages/About";
import Contact from "../pages/Contact";
export { Home, Login, Register, Logout, View, Create, Edit,Delete , About , Contact};
